TITLE Mod file for component: Component(id=ca_conc type=decayingPoolConcentrationModel_Anwar)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.7.0
         org.neuroml.model   v1.7.0
         jLEMS               v0.10.2

ENDCOMMENT

NEURON {
    SUFFIX ca_conc
    USEION ca READ cao, ica WRITE cai VALENCE 2
    RANGE cai
    RANGE cao
    RANGE restingConc                       : parameter
    RANGE decayConstant                     : parameter
    RANGE shellDepth                        : parameter
    RANGE Faraday                           : parameter
    RANGE AREA_SCALE                        : parameter
    RANGE LENGTH_SCALE                      : parameter
    RANGE effectiveRadius                   : derived variable
    RANGE eqshellDepth                      : derived variable
    RANGE innerRadius                       : derived variable
    RANGE shellVolume                       : derived variable
}

UNITS {
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
}

PARAMETER {
    initialConcentration (mM)
    initialExtConcentration (mM)
    restingConc = 0 (mM)
    decayConstant = 33.333336 (ms)
    shellDepth = 0.1 (um)
    Faraday = 0.0964853 (C / umol)
    AREA_SCALE = 1.0E12 (um2)
    LENGTH_SCALE = 1000000 (um)
}

ASSIGNED {
    diam (um)
    area (um2)
    effectiveRadius (um)                   : derived variable
    eqshellDepth (um)                      : derived variable
    innerRadius (um)                       : derived variable
    shellVolume (um3)                      : derived variable
    rate_concentration (mM/ms)
}

STATE {
    concentration (mM) 
    extConcentration (mM) 
    surfaceArea (um2)
    iCanA (nA)
}

INITIAL {
    rates(ica)
    rates(ica) ? To ensure correct initialisation.
    concentration = cai
    extConcentration = cao
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    if (concentration  < 0) {
        concentration = 0 ? standard OnCondition
    }
}

DERIVATIVE states {
    rates(ica)
    concentration' = rate_concentration
    cai = concentration
}

PROCEDURE rates(icaa) {
    surfaceArea = area   : surfaceArea has units (um2), area (built in to NEURON) is in um^2...
    iCanA = -1 * (0.01) * icaa * surfaceArea :   iCanA has units (nA) ; ica (built in to NEURON) has units (mA/cm2)...
    effectiveRadius = LENGTH_SCALE  * (surfaceArea/(  AREA_SCALE   * (4 * 3.14159)))^0.5 ? evaluable
    eqshellDepth = shellDepth  - ((  shellDepth   *   shellDepth  ) /   effectiveRadius  ) ? evaluable
    innerRadius = effectiveRadius  -  eqshellDepth ? evaluable
    shellVolume = (4 * (  effectiveRadius   *  effectiveRadius  *   effectiveRadius  ) * 3.14159 / 3) - (4 * (  innerRadius   *  innerRadius  *   innerRadius  ) * 3.14159 / 3) ? evaluable
    rate_concentration = ((iCanA /surfaceArea) / (2 *  Faraday  *   eqshellDepth  )) - ((  concentration   -   restingConc  ) /   decayConstant  ) ? Note units of all quantities used here need to be consistent!
}

